### ISSUE TITLE
Error in LiveTranslator\Panel

### ISSUE THREAD

**Issue by Petrik-a-dost** [VladaHejda/LiveTranslator#18]
Ahojky,

nevím co dělám špatně, ale po předepsaném nastavení mi to háže v Tracy info:
ErrorException: Nette\Templating\FileTemplate is deprecated. in /data/web/virtuals/169469/virtual/vendor/nette/deprecated/src/Templating/FileTemplate.php:31
Stack trace:
#0 [internal function]: Tracy\Bar->Tracy\{closure}(16384, 'Nette\\Templatin...', '/data/web/virtu...', 31, Array)
#1 /data/web/virtuals/169469/virtual/vendor/nette/deprecated/src/Templating/FileTemplate.php(31): trigger_error('Nette\\Templatin...', 16384)
#2 /data/web/virtuals/169469/virtual/vendor/vladahejda/livetranslator/LiveTranslator/Panel/Panel.php(98): Nette\Templating\FileTemplate->__construct('/data/web/virtu...')
#3 /data/web/virtuals/169469/virtual/vendor/tracy/tracy/src/Tracy/Bar.php(152): LiveTranslator\Panel->getTab()
#4 /data/web/virtuals/169469/virtual/vendor/tracy/tracy/src/Tracy/Bar.php(108): Tracy\Bar->renderPanels()
#5 /data/web/virtuals/169469/virtual/vendor/tracy/tracy/src/Tracy/Debugger.php(266): Tracy\Bar->render()
#6 [internal function]: Tracy\Debugger::shutdownHandler()
#7 {main}

koukal jse že je to pro nette 2.
Já mam nette 2.4, php 7.0.19, LiveTranslator 1.0.0-rc
jen jsem musel v config.neon upravit  "nette: debugger: bar:" na "tracy: bar:"
nevíte kde by mohla být chyba?

Předem děkuji za odpověď.

Petr

**Comment by bckp** [comment]
Řekl bych že LiveTranslator je dead....
